name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.0.1
      with:
        # Target architecture
        arch: x64
        # Windows SDK number to build for
        #sdk: # optional
        # Enable Specre mitigations
        #spectre: # optional
        # VC++ compiler toolset version
        toolset: 12.xx
        # Build for Universal Windows Platform
        #uwp: # optional
